apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-buba
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-buba
    app.kubernetes.io/part-of: harry-test
  name: devfile-sample-buba
  namespace: halawren-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-buba
status:
  loadBalancer: {}
